version: 0.11

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-1 s3 sync ./dist/ s3://makeyourlab-code-bucket/ --acl=public-read --delete
